### ISSUE TITLE
Date Formats

### ISSUE THREAD

**Issue by mbwhite** [Jackson-Wozniak/Stock-Market-Simulation#12]
Hello @Jackson-Wozniak  - I've been running a few longer running tests; and thinking about how to visualize the markets;  recently I've been introduced to jupyter-notebooks and this has proved to be very useful. But I've hit a bit of a blocker - the dates. 

I've worked for a US company for years so I'm (almost) comfortable with the month/day/year date format; the last run though showed that the simulation can produce the 30th of February:

Wondered what your thoughts where about modifying the dates used - to head to the ISO format date? Can be easily parsed by standard libraries and converted as needed. 

Don't mind doing this myself - but wanted to run it past you first.

**Comment by Jackson-Wozniak** [comment]
Yeah that sounds like a great idea! When I originally wrote the code for the dates I just chose 30 day periods to act as months, as opposed to modelling the real calendar, so I think it would be a good idea to update this

**Comment by mbwhite** [comment]
Thanks @Jackson-Wozniak  - initial updates seem to be stable so far... 

![image](https://github.com/Jackson-Wozniak/Stock-Market-Simulation/assets/6673453/5f55fd64-101f-4efb-b159-be871a625322)

**Comment by mbwhite** [comment]
Hello - I've made the changes in this branch in my fork.. https://github.com/mercatia/Stock-Market-Simulation/tree/ISOTime

Reasonably extensive; but so far so good!  Can make a PR if you'd like, but you're welcome to pull the changes and adapt if you wish.
