### ISSUE TITLE
Update README.md api endpoint urls

### ISSUE THREAD

**Issue by Jackson-Wozniak** [Jackson-Wozniak/Stock-Market-Simulation#8]

**Comment by ankman007** [comment]
Hey i'm looking to make my first contribution here. I am well versed in java programming language and would love to make contribution to this repo whether it be code or documentation. Just let me how I can help.

**Comment by Jackson-Wozniak** [comment]
If you would like to help with documentation, some of the endpoints in the README.md have not been updated to match the paths in the controllers. If you wanted to update some of the endpoints for Stocks, Index Funds or Accounts that would be great! You can find the updated paths in each of their controllers in the src folder.

As for coding contributions, I am not entirely sure what features I want to add yet. I was thinking of adding Options Trading and a Trading Bot, however I haven't planned out how I wanted to do it yet. If you have any ideas that you think would be interesting, you can let me know

**Comment by ankman007** [comment]
Okay I will look into README.md and update the outdated links. Unfortunately I don't think I can help you much with the coding contributions, sounds too complicated for me.
